python oscar/run_captioning.py \
--model_name_or_path=../output/scst/checkpoint-2-74000 \
--data_dir=../datasets/coco_caption \
--do_train \
--evaluate_during_training \
--do_lower_case \
--add_od_labels \
--learning_rate=0.00001 \
--per_gpu_train_batch_size=1 \
--num_train_epochs=75 \
--tie_weights \
--freeze_embedding \
--scst \
--save_steps=2000 \
--output_dir=../output/scst/
