AMP_VERBOSE: False
CUDNN_BENCHMARK_ON_FEATURE_EXTRACTION: False
DATALOADER:
  ASPECT_RATIO_GROUPING: True
  NUM_WORKERS: 4
  SHARING_STRATEGY: file_descriptor
  SIZE_DIVISIBILITY: 32
DATASETS:
  ATTR_LABELMAP_FILE: 
  BOX_EXTRA_FIELDS: ()
  FACTORY_TEST: ('VGTSVDataset', 'ODTSVDataset', 'OpenImagesTSVDataset', 'ODTSVDataset')
  FACTORY_TRAIN: ('VGTSVDataset', 'ODTSVDataset', 'OpenImagesTSVDataset', 'ODTSVDataset')
  HIERARCHY_FILE: 
  LABELMAP_FILE: 
  TEST: ('visualgenome/test_vgoi6_clipped_4djoint.yaml', 'coco/COCO_vgoiv6_val.yaml', 'openimages_v5c/val_vgoiv6.yaml', 'Objects365/val_vgoiv6.yaml')
  TRAIN: ('visualgenome/train_vgoi6_clipped_8copy.yaml', 'coco/COCO_vgoiv6_train_8copy.yaml', 'openimages_v5c/train_vgoiv6.cas.2000.yaml', 'Objects365/objects365_train_vgoiv6.cas2000_2copy.yaml')
DATA_DIR: /mnt/default/data/maskrcnn/datasets
DISTRIBUTED_BACKEND: gloo
DTYPE: float32
INPUT:
  BRIGHTNESS: 0.0
  CONTRAST: 0.0
  CROP_IOU_THRESH: 0.5
  CROP_MAX_SCALE: 1.0
  CROP_MIN_SCALE: 0.3
  CV2_OUTPUT: False
  FLIP_PROB_TRAIN: 0.5
  HUE: 0.0
  MAX_SIZE_TEST: 1000
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 600
  MIN_SIZE_TRAIN: (448, 512, 576, 640, 704, 768, 800)
  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [1.0, 1.0, 1.0]
  RANDOM_CROP_TRAIN: False
  SATURATION: 0.0
  TO_BGR255: True
  VERTICAL_FLIP_PROB_TRAIN: 0.0
LOG_GRAD_NORM: False
LOG_LOSS_PERIOD: 20
MODEL:
  ATTRIBUTE_ON: False
  BACKBONE:
    CONV_BODY: R-152-C4
    FREEZE_CONV_BODY_AT: 2
    USE_BN: False
  CASCADE_IOU: (0.5,)
  CASCADE_LEVEL: -1
  CASCADE_LOSS_WEIGHTS: (1.0,)
  CLASSIFICATION_ON: False
  CLASSIFIER:
    ADD_BOX_CHANNEL: False
    ARCH: resnet50
    HAS_NEGATIVE_LABEL: False
    INPUT_SIZE: 224
    NUM_CLASSES: 500
    PAD_RATIO: 0.25
  CLS_AGNOSTIC_BBOX_REG: False
  DEVICE: cuda
  FBNET:
    ARCH: default
    ARCH_DEF: 
    BN_TYPE: bn
    DET_HEAD_BLOCKS: []
    DET_HEAD_LAST_SCALE: 1.0
    DET_HEAD_STRIDE: 0
    DW_CONV_SKIP_BN: True
    DW_CONV_SKIP_RELU: True
    KPTS_HEAD_BLOCKS: []
    KPTS_HEAD_LAST_SCALE: 0.0
    KPTS_HEAD_STRIDE: 0
    MASK_HEAD_BLOCKS: []
    MASK_HEAD_LAST_SCALE: 0.0
    MASK_HEAD_STRIDE: 0
    RPN_BN_TYPE: 
    RPN_HEAD_BLOCKS: 0
    SCALE_FACTOR: 1.0
    WIDTH_DIVISOR: 1
  FPN:
    USE_GN: False
    USE_RELU: False
  FREEZE_WEIGHTS_ITER: -1
  FREEZE_WEIGHTS_REGEXP: 
  FREQ_PRIOR: visualgenome/label_danfeiX_clipped.freq_prior.npy
  GRID_SAMPLER: random
  GROUP_NORM:
    DIM_PER_GP: -1
    EPSILON: 1e-05
    NUM_GROUPS: 32
  KEYPOINT_ON: False
  MASK_ON: False
  META_ARCHITECTURE: GeneralizedRCNN
  RELATION_ON: False
  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
    BATCHNORM_EPS: 0.0
    DEFORMABLE_GROUPS: 1
    IN_CHANNELS: (64, 128, 256, 512)
    LAYERS: (3, 4, 6, 3)
    NUM_GROUPS: 32
    RES2_OUT_CHANNELS: 256
    RES5_DILATION: 1
    STAGE_WITH_DCN: (False, False, False, False)
    STEM_FUNC: StemWithFixedBatchNorm
    STEM_OUT_CHANNELS: 64
    STEM_PADDING_MODE: pad
    STRIDE_IN_1X1: False
    TRANS_FUNC: BottleneckWithFixedBatchNorm
    USE_SE: False
    WIDTH_PER_GROUP: 8
    WITH_MODULATED_DCN: False
  RETINANET:
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDES: (8, 16, 32, 64, 128)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    BBOX_REG_BETA: 0.11
    BBOX_REG_WEIGHT: 4.0
    BG_IOU_THRESHOLD: 0.4
    FG_IOU_THRESHOLD: 0.5
    INFERENCE_TH: 0.05
    LOSS_ALPHA: 0.25
    LOSS_GAMMA: 2.0
    MAX_NUM_ATTR_PER_IMG: 100
    MAX_NUM_ATTR_PER_OBJ: 16
    NMS_TH: 0.4
    NUM_ATTRIBUTES: 100
    NUM_CLASSES: 81
    NUM_CONVS: 4
    OCTAVE: 2.0
    PRE_NMS_TOP_N: 1000
    PRIOR_PROB: 0.01
    SCALES_PER_OCTAVE: 3
    STRADDLE_THRESH: 0
    USE_C5: True
  RETINANET_ON: False
  ROI_ATTRIBUTE_HEAD:
    ALIGNEDLABELMAP: 
    ATTR_EMD_DIM: 512
    CLS_EMD_DIM: 256
    FEATURE_EXTRACTOR: ResNet50Conv5ROIFeatureExtractor
    LOSS_WEIGHT: 0.5
    MAX_NUM_ATTR_PER_IMG: 100
    MAX_NUM_ATTR_PER_OBJ: 16
    MLP_HEAD_DIM: 1024
    NUM_ALIGNED_CLASSES: -1
    NUM_ATTRIBUTES: 525
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES: (0.0625,)
    POSTPROCESS_ATTRIBUTES_THRESHOLD: 0.0
    PREDICTOR: AttributeRCNNPredictor
    SHARE_BOX_FEATURE_EXTRACTOR: True
  ROI_BOX_HEAD:
    CONV_HEAD_DIM: 256
    DILATION: 1
    FEATURE_EXTRACTOR: ResNet50Conv5ROIFeatureExtractor
    FORCE_BOXES: False
    IGNORE_CLS_THRESH: 0.5
    IGNORE_OBJ_THRESH: 0.7
    LOSS_WEIGHT_POS: 20
    MLP_HEAD_DIM: 1024
    NUM_CLASSES: 1849
    NUM_STACKED_CONVS: 4
    ONLINE_LABEL_IGNORE: False
    POOLER_LEVEL: -1
    POOLER_LEVEL_MAPPING: True
    POOLER_MERGE_TYPE: concat
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES: (0.0625,)
    POOLER_TYPE: ROIAlign
    PREDICTOR: FastRCNNPredictor
    USE_GN: False
    USE_SAMPLE_CONFIDENCE: False
    USE_SOFT_SAMPLING: False
  ROI_CLASSIFICATION_HEAD:
    BACKGROUND_CLASS_ON: True
    CONV_LAYERS: (512, 512, 512, 1024)
    CONV_STRIDES: (1, 1, 1, 2)
    FC_LAYERS: (1024, 1024)
    FEATURE_EXTRACTOR: FPNConvFeatureExtractor
    LOSS_WEIGHT: 0.2
    LOSS_WEIGHT_FOR_UNKNOWN_CLASS: 0.1
    NUM_CLASSES: 6405
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES: (0.0625,)
    PREDICTOR: FCPredictor
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 384
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0)
    BG_IOU_THRESHOLD: 0.5
    DETECTIONS_PER_IMG: 100
    FG_IOU_THRESHOLD: 0.5
    MIN_DETECTIONS_PER_IMG: 10
    NMS: 0.5
    NMS_TYPE: nms
    NM_FILTER: 0
    POSITIVE_FRACTION: 0.5
    SCORE_THRESH: 0.05
    SOFTNMS:
      IOU_THRESH: 0.01
      METHOD: 2
      SCORE_THRESH: 0.0001
      SIGMA: 0.2
    USE_FPN: False
    VOTING:
      ENABLED: False
      IOU_THRESH: 0.8
      SCORE_MODE: max
  ROI_KEYPOINT_HEAD:
    CONV_LAYERS: (512, 512, 512, 512, 512, 512, 512, 512)
    FEATURE_EXTRACTOR: KeypointRCNNFeatureExtractor
    MLP_HEAD_DIM: 1024
    NUM_CLASSES: 17
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES: (0.0625,)
    PREDICTOR: KeypointRCNNPredictor
    RESOLUTION: 14
    SHARE_BOX_FEATURE_EXTRACTOR: True
  ROI_MASK_HEAD:
    BOX_MASK_WEIGHT: 0.5
    CONV_LAYERS: (256, 256, 256, 256)
    DILATION: 1
    FEATURE_EXTRACTOR: ResNet50Conv5ROIFeatureExtractor
    MASK_MODE: poly
    MLP_HEAD_DIM: 1024
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES: (0.0625,)
    POSTPROCESS_MASKS: False
    POSTPROCESS_MASKS_THRESHOLD: 0.5
    PREDICTOR: MaskRCNNC4Predictor
    RESOLUTION: 14
    SHARE_BOX_FEATURE_EXTRACTOR: True
    USE_GN: False
  ROI_RELATION_HEAD:
    ALGORITHM: sg_baseline
    BACKBONE_FREEZE_PARAMETER: True
    BATCH_SIZE_PER_IMAGE: 512
    CONTRASTIVE_LOSS:
      FG_REL_FRACTION: 0.25
      FG_REL_SIZE_PER_IM: 512
      USE_FLAG: False
    CONV_HEAD_DIM: 256
    DILATION: 1
    FEATURE_EXTRACTOR: ResNet50Conv5ROIRelationFeatureExtractor
    FILTER_NON_OVERLAP: True
    FORCE_RELATIONS: False
    GRCNN_FEATURE_UPDATE_STEP: 0
    GRCNN_SCORE_UPDATE_STEP: 0
    IMP_FEATURE_UPDATE_STEP: 0
    MLP_HEAD_DIM: 1024
    MODE: sgdet
    MSDN_FEATURE_UPDATE_STEP: 0
    NEURAL_MOTIF:
      DEBUG: False
      DROPOUT: 0.0
      EDGE_LSTM_NUM_LAYERS: 4
      EMBED_DIM: 100
      GLOVE_PATH: glove/
      HIDDEN_DIM: 256
      NUM_OBJS: 64
      OBJ_CLASSES_FN: visualgenome/label_danfeiX_clipped.obj_classes.txt
      OBJ_FEAT_TO_DECODER: False
      OBJ_FEAT_TO_EDGE: False
      OBJ_LSTM_NUM_LAYERS: 2
      ORDER: confidence
      POS_BATCHNORM_MOMENTUM: 0.001
      POS_EMBED_DIM: 128
      REL_CLASSES_FN: visualgenome/label_danfeiX_clipped.rel_classes.txt
      USE_TANH: False
    NUM_CLASSES: 51
    NUM_STACKED_CONVS: 4
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES: (0.0625,)
    POSITIVE_FRACTION: 0.25
    PREDICTOR: FastRCNNRelationPredictor
    ROI_BOX_HEAD_FREEZE_PARAMETER: True
    RPN_FREEZE_PARAMETER: True
    SHARE_BOX_FEATURE_EXTRACTOR: False
    TRIPLETS_PER_IMG: 100
    UPDATE_BOX_REG: False
    USE_BIAS: False
    USE_GN: False
    USE_RELPN: False
  RPN:
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (16,)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    BATCH_SIZE_PER_IMAGE: 256
    BG_IOU_THRESHOLD: 0.3
    FG_IOU_THRESHOLD: 0.7
    FORCE_BOXES: False
    FPN_POST_NMS_TOP_N_TEST: 2000
    FPN_POST_NMS_TOP_N_TRAIN: 2000
    HIDDEN_FEAT_DIM: 0
    MIN_SIZE: 0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOP_N_TEST: 300
    POST_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 6000
    PRE_NMS_TOP_N_TRAIN: 12000
    RPN_HEAD: SingleConvRPNHead
    STRADDLE_THRESH: 0
    USE_FPN: False
    USE_SAMPLE_CONFIDENCE: False
    USE_SOFT_SAMPLING: False
    X2Y2CORRECTION: -1
  RPN_ONLY: False
  SCAN:
    AGG_FUNC: LogSumExp
    AVERAGE_LOSS: True
    BBOX_AS_INPUT: False
    BI_GRU: True
    CROSS_ATTN: t2i
    EMBED_SIZE: 1024
    FEATURES_AS_INPUT: False
    FREEZE_BACKBONE: False
    IMG_FEATURES_DIM: 1024
    JOINT_TASK: -1
    LAMBDA_LSE: 6.0
    LAMBDA_SOFTMAX: 9.0
    MARGIN: 0.2
    MAX_VIOLATION: True
    NO_IMG_NORM: False
    NO_TXT_NORM: False
    NUM_CAPTIONS_PER_IMG: 5
    NUM_LAYERS: 1
    PRECOMP_ENC_TYPE: basic
    RANDOM_BOXES: False
    RAW_FEATURE_NORM: clipped_l2norm
    TEXT_FEATURES_AS_INPUT: False
    TEXT_FEATURES_DIM: 1024
    VISUALIZE_ATTENTION_IDS: []
    VOCAB_SIZE: 11353
    WORD_DIM: 300
  SKIP_UNMATCHED_LAYERS_TRAIN: True
  USE_CLASSIFIER: False
  USE_FREQ_PRIOR: False
  USE_SCAN: False
  WEIGHT: /mnt/my_storage/multitask/attr_frcnn_X152C4configs/multitask/attr_frcnn_X152C4.yaml_pos0.25_lr0.005_bsz16/model_final.pth
MULTI_TASK:
  CONFIGS: []
  ENFORCE_UNUSED_PARAMS: False
  LOSS_WEIGHTS: []
  SHARE_BACKBONE: False
  SHARE_FEATURE_EXTRACTOR: False
  SHARE_RPN: False
  TASK_ITERS: []
OUTPUT_DIR: /mnt/my_storage/multitask/attr_frcnn_X152C4continue_configs/multitask/attr_frcnn_X152C4.yaml_pos0.5_lr0.002_bsz16_drop160000
PATHS_CATALOG: /mnt/batch/tasks/shared/LS_root/jobs/usscv100ws/azureml/pt-x152c4_continue_4sets_trai-39b656c6_1601002528_7c25a4e7/mounts/workspaceblobstore/azureml/pt-X152C4_continue_4sets_trai-39b656c6_1601002528_7c25a4e7/maskrcnn_benchmark/config/paths_catalog.py
SOLVER:
  BASE_LR: 0.002
  BIAS_LR_FACTOR: 2
  BROADCAST_BUFFERS: False
  CHECKPOINT_PERIOD: 10000
  CLIP_MAX_NORM: 10.0
  GAMMA: 0.1
  GRAD_CLIP: False
  GRAD_CLIP_REGEXP: 
  IMS_PER_BATCH: 16
  LR_POLICY: multistep
  MAX_ITER: 300000
  MIN_LR: 0.0001
  MOMENTUM: 0.9
  OPTIMIZER: sgd
  REDUCE_LOSS: False
  REGEXP_LR_FACTOR: ()
  REGEXP_MULTITASK_SHARED: ()
  STEPS: (160000, 240000.0)
  USE_LARC: False
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 4000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 5e-05
  WEIGHT_DECAY_BIAS: 0.0
TEST:
  ACCUMULATE_SCORES: False
  BBOX_AUG:
    ENABLED: False
    H_FLIP: False
    MAX_SIZE: 4000
    SCALES: ()
    SCALE_H_FLIP: False
  BOX_ACTIVATION_FUNC: softmax
  BOX_MIN_SIZE: 0
  CONCAT_PREDICTIONS: False
  DETECTIONS_PER_IMG: 100
  EXPECTED_RESULTS: []
  EXPECTED_RESULTS_SIGMA_TOL: 4
  FOR_CAPTIONING:
    ENABLED: False
    FOLDER_NAME: 
    OVERWRITE: False
  GATHER_ON_CPU: True
  IGNORE_BOX_REGRESSION: False
  IMS_PER_BATCH: 16
  OUTPUT_FEATURE: False
  OUTPUT_SCORES_ALL: False
  SAVE_PREDICTIONS: False
  SAVE_RESULTS_TO_TSV: True
  SKIP_PERFORMANCE_EVAL: False
  TSV_SAVE_SUBSET: ['rect', 'class', 'conf']
USE_TENSORBOARD_LOGS: True