python oscar/run_captioning.py \
--model_name_or_path=../output/coco_ru_base_xe_3/checkpoint-28-250000 \
--data_dir=/mnt/ssd/coco/coco_oscar_preexacted_vvl \
--do_train \
--evaluate_during_training \
--add_od_labels \
--scheduler=constant \
--learning_rate=3e-6 \
--per_gpu_train_batch_size=1 \
--per_gpu_eval_batch_size=16 \
--gradient_accumulation_steps=4 \
--num_train_epochs=50 \
--tie_weights \
--freeze_embedding \
--scst \
--num_workers=0 \
--logging_steps=100 \
--save_steps=2000 \
--output_dir=../output/coco_ru_base_xe_3_scst/ \
--fp16
